name: Close Pull Request Action

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  node_version: '18.x'
  app_name: 'ui'

jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --sas-token ${{ secrets.AZURE_CREDENTIALS }} --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} --source ${{ vars.BUNDLES_CONTAINER_NAME}} --pattern "bundles/${{ env.app_name }}/${{ github.ref_name }}/*"
