name: New Pull Request Action

on:
  pull_request:
    branches:
      - main
    types:
      - opened

env:
  node_version: '18.x'
  app_name: 'ui'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ env.node_version }}-build-${{ hashFiles('package.json') }}

      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Unit Tests
        run: npm run test

      - name: Build
        run: npm build

      - name: Storybook Tests
        run: npm run storybook:test

      - name: Storybook Build
        run: npm run storybook:build

      - name: Changed Package Paths
        run: echo "CHANGED_PACKAGE_PATHS=$(for pkg in $(lerna changed | xargs); do echo 'packages/$pkg/storybook-static'; done)" >> $GITHUB_ENV

      - name: Changed Package URLs
        run: echo "CHANGED_PACKAGE_URLS=$(for pkg in $(lerna changed | xargs); do echo 'https://ui.arkitema.com/${{ github.ref_name }}/$pkg/'; done)" >> $GITHUB_ENV

      - name: Upload Storybook Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: storybooks
          path: |
            ${{ env.CHANGED_PACKAGE_PATHS }}

      - name: Create Comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Changed Storybooks can be found at:
            ${{ env.CHANGED_PACKAGE_URLS }}

  publish-storybook:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v3
        with:
          name: storybooks

      - name: Upload to Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch \
              --sas-token ${{ secrets.AZURE_STORAGE_CREDENTIALS }} \
              --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
              --source ${{ vars.BUNDLES_CONTAINER_NAME}} \
              --pattern "bundles/${{ env.app_name }}/${{ github.ref_name }}/*"
            az storage blob upload-batch \
              --sas-token ${{ secrets.AZURE_STORAGE_CREDENTIALS }} \
              --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
              --auth-mode key -d ${{ vars.BUNDLES_CONTAINER_NAME}} \
              --destination-path "bundles/${{ env.app_name }}/${{ github.ref_name }}" \
              -s ./packages \
              --pattern **/storybook-static/*
