name: New Pull Request Action

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

env:
  node_version: '18.x'
  app_name: 'ui'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        package: ["brand", "datafetching", "errorhandling", "inputs", "layout", "navigation", "pages", "visualizations"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ env.node_version }}-build-${{ hashFiles('package-lock.json') }}

      - name: Cache Build Artifacts
        id: cache-build-artifacts
        uses: actions/cache@v3
        with:
          path: packages/${{ matrix.package }}/dist
          key: ${{ matrix.package }}-build-${{ hashFiles('packages/${{ matrix.package }}') }}

      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        run: npm run lint -w packages/${{ matrix.package }}

      - name: Format
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        run: npm run format -w packages/${{ matrix.package }}

      - name: Build
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        run: npm run build -w packages/${{ matrix.package }}

      - name: Unit Tests
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        run: npm run test:coverage -w packages/${{ matrix.package }}

      - name: 'Report Coverage'
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: ${{ matrix.package }}
          json-summary-path: packages/${{ matrix.package }}/coverage/coverage-summary-${{ matrix.package }}.json
          json-final-path: packages/${{ matrix.package }}/coverage/coverage-final-${{ matrix.package }}.json'

      - name: Storybook Tests
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        run: npm run storybook:test -w packages/${{ matrix.package }}

      - name: Storybook Build
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        run: npm run storybook:build -w packages/${{ matrix.package }}

      - name: Upload Storybook Artifacts
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v3
        with:
          name: storybook-${{ matrix.package }}
          path: packages/${{ matrix.package }}/storybook-static

      - name: Create Comment on PR
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Changed Storybook: ${{ matrix.package }} can be found at:
            https://ui.arkitema.com/${{ github.ref_name }}/${{ matrix.package }}/

      - name: Upload to Blob Storage
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch \
              --sas-token ${{ secrets.AZURE_STORAGE_CREDENTIALS }} \
              --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
              --source ${{ vars.BUNDLES_CONTAINER_NAME}} \
              --pattern "bundles/${{ env.app_name }}/${{ github.ref_name }}/${{ matrix.package }}/*"
            az storage blob upload-batch \
              --sas-token ${{ secrets.AZURE_STORAGE_CREDENTIALS }} \
              --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
              --auth-mode key -d ${{ vars.BUNDLES_CONTAINER_NAME}} \
              --destination-path "bundles/${{ env.app_name }}/${{ github.ref_name }}/${{ matrix.package }}" \
              -s ./packages/${{ matrix.package }}/storybook-static
